kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ray
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ray
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ray
subjects:
- kind: ServiceAccount
  name: ray
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ray-ds
  namespace: kube-system
  labels:
    app: ray-operator
spec:
  template:
    metadata:
      labels:
        app: ray-operator
    spec:
      serviceAccountName: ray  
      containers:
      - name: ray-operator
        image: ray-operator:latest
        command: ["/bin/sh"]
        args:["-c","./ray-controller --v 4 --alsologtostderr"]
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"

